name: Deploy Docs

on:
  push:
    branches:
      - main  # Укажите вашу основную ветку, если это не 'main', а, например, 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install mkdocs
        pip install mkdocs-material
        pip install mike

    - name: Set git user info
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Checkout gh-pages branch
      run: |
        git fetch origin gh-pages
        git checkout gh-pages
        git merge origin/gh-pages --allow-unrelated-histories --no-edit
        git push origin gh-pages

    - name: Build the docs
      run: mkdocs build -f docs-repo/mkdocs.yml  # Убедитесь, что путь к mkdocs.yml указан правильно

    - name: Deploy documentation to GitHub Pages
      run: |
        mike deploy v4.5.0 --push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
